repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3.9
        additional_dependencies: ['click==8.0.4']
        args: ["--skip-string-normalization", "--line-length", "120"]

-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies:
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-tidy-imports
        - flake8-eradicate
        - flake8-print
        - flake8-simplify